name: auraascend
description: "Fix your damn life with AurAchieve."
publish_to: 'none'
version: 0.1.13+8

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^20.3.2
  flutter_svg: ^2.0.10
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2
  dynamic_color: ^1.6.6
  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.1
  confetti: ^0.8.0
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.4.0
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  vector_math: ^2.2.0
  wakelock_plus: ^1.3.3
  image_cropper: ^11.0.0
  flutter_image_compress: ^2.4.0
  url_launcher: ^6.3.2
  lottie: ^3.3.2
  flutter_markdown: ^0.7.7+1
  flutter_quill: ^11.5.0
  file_picker: ^10.3.8
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  local_auth: ^3.0.0
  encrypt: ^5.0.3
  emoji_picker_flutter: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/img/
  - assets/icon/
  - assets/anim/